# Generated by Django 5.2.11 on 2026-05-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empl_surname', models.CharField(max_length=50)),
                ('empl_name', models.CharField(max_length=50)),
                ('empl_patronymic', models.CharField(blank=True, max_length=50, null=True)),
                ('empl_role', models.CharField(choices=[('Manager', 'Manager'), ('Cashier', 'Cashier')], max_length=10)),
                ('salary', models.DecimalField(decimal_places=4, max_digits=13)),
                ('date_of_birth', models.DateField()),
                ('date_of_start', models.DateField()),
                ('phone_number', models.CharField(max_length=13)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=9)),
            ],
        ),
    ]
