# Generated by Django 5.2.11 on 2026-05-16 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee',
            field=models.OneToOneField(db_column='id_employee', null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
    ]
