# Generated by Django 5.2.11 on 2026-05-16 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_update_user_employee_constrains'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee',
            field=models.OneToOneField(db_column='id_employee', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee'),
        ),
    ]
