# Generated by Django 5.2.11 on 2026-05-23 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_surname', models.CharField(max_length=50)),
                ('cust_name', models.CharField(max_length=50)),
                ('cust_patronymic', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=13)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=9, null=True)),
                ('percent', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
