# Generated by Django 5.2.11 on 2026-05-23 18:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('employees', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_date', models.DateTimeField()),
                ('sum_total', models.DecimalField(decimal_places=4, max_digits=13, validators=[django.core.validators.MinValueValidator(0)])),
                ('vat', models.DecimalField(decimal_places=4, max_digits=13, validators=[django.core.validators.MinValueValidator(0)])),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customercard')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('pk', models.CompositePrimaryKey('UPC', 'check_number', blank=True, editable=False, primary_key=True, serialize=False)),
                ('product_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('selling_price', models.DecimalField(decimal_places=4, max_digits=13, validators=[django.core.validators.MinValueValidator(0)])),
                ('UPC', models.ForeignKey(db_column='UPC', on_delete=django.db.models.deletion.DO_NOTHING, to='products.storeproduct')),
                ('check_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.check')),
            ],
        ),
    ]
