# Generated by Django 5.2.14 on 2026-05-13 19:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('check_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('print_date', models.DateTimeField()),
                ('sum_total', models.DecimalField(decimal_places=4, max_digits=13, validators=[django.core.validators.MinValueValidator(0)])),
                ('vat', models.DecimalField(decimal_places=4, max_digits=13, validators=[django.core.validators.MinValueValidator(0)])),
                ('card_number', models.ForeignKey(blank=True, db_column='card_number', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customercard')),
                ('id_employee', models.ForeignKey(db_column='id_employee', on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employee')),
            ],
        ),
    ]
