# Generated by Django 5.2.11 on 2026-05-16 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_storeproduct'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('pk', models.CompositePrimaryKey('UPC', 'check_number', blank=True, editable=False, primary_key=True, serialize=False)),
                ('product_number', models.IntegerField()),
                ('selling_price', models.DecimalField(decimal_places=4, max_digits=13)),
                ('UPC', models.ForeignKey(db_column='UPC', on_delete=django.db.models.deletion.DO_NOTHING, to='products.storeproduct')),
                ('check_number', models.ForeignKey(db_column='check_number', on_delete=django.db.models.deletion.CASCADE, to='sales.check')),
            ],
        ),
    ]
