# Generated by Django 5.2.14 on 2026-05-21 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_update_check_sale_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='product_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='selling_price',
            field=models.DecimalField(decimal_places=4, max_digits=13, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
