# Generated by Django 5.2.11 on 2026-05-23 18:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('characteristics', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('UPC', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('selling_price', models.DecimalField(decimal_places=4, max_digits=13, validators=[django.core.validators.MinValueValidator(0)])),
                ('products_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('promotional_product', models.BooleanField()),
                ('UPC_prom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.storeproduct')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product')),
            ],
        ),
    ]
