# Generated by Django 5.2.14 on 2026-05-15 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('characteristics', models.CharField(max_length=100)),
                ('category_number', models.ForeignKey(db_column='category_number', on_delete=django.db.models.deletion.RESTRICT, to='products.category')),
            ],
        ),
    ]
