# Generated by Django 6.0.5 on 2026-05-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
