# Generated by Django 5.2.11 on 2026-05-16 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_category_category_number_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.category'),
        ),
    ]
