# Generated by Django 5.2.11 on 2026-05-16 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_category_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('UPC', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('selling_price', models.DecimalField(decimal_places=4, max_digits=13)),
                ('products_number', models.IntegerField()),
                ('promotional_product', models.BooleanField()),
                ('UPC_prom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.storeproduct')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.product')),
            ],
        ),
    ]
