# Generated by Django 5.2.11 on 2026-06-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
