# Generated by Django 5.2.11 on 2026-05-16 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_storeproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.category'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product'),
        ),
    ]
