# Generated by Django 5.2.14 on 2026-05-21 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_update_product_store_product_category_constrains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproduct',
            name='products_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='selling_price',
            field=models.DecimalField(decimal_places=4, max_digits=13, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
